{{- if and (eq .Values.mode "aio") .Values.aio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observer.fullname" . }}-aio
  labels:
    {{- include "observer.labels" . | nindent 4 }}
    app.kubernetes.io/component: aio
spec:
  type: {{ .Values.aio.service.type }}
  ports:
  - port: {{ .Values.aio.service.webPort }}
    targetPort: web
    protocol: TCP
    name: web
  - port: {{ .Values.aio.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: 8081
    targetPort: health
    protocol: TCP
    name: health
  - port: {{ .Values.aio.service.apiPort }}
    targetPort: api
    protocol: TCP
    name: api
  - port: {{ .Values.aio.service.natsPort }}
    targetPort: nats
    protocol: TCP
    name: nats
  - port: {{ .Values.aio.service.natsMonitoringPort }}
    targetPort: nats-monitor
    protocol: TCP
    name: nats-monitor
  selector:
    {{- include "observer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: aio
{{- end }}
