apiVersion: v2
name: observer
description: A Helm chart for Observer - Test Observability System
type: application
version: 0.7.0-beta
appVersion: "0.7.0-beta"
icon: https://raw.githubusercontent.com/stanterprise/observer/master/web/public/favicon.ico
keywords:
  - testing
  - observability
  - grpc
  - nats
home: https://github.com/stanterprise/observer
sources:
  - https://github.com/stanterprise/observer
maintainers:
  - name: Stanterprise Team
    url: https://github.com/stanterprise
dependencies:
  - name: postgresql
    version: "~16.7.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mongodb
    version: "~16.3.0"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: nats
    version: "~1.2.0"
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
