DROP TABLE IF EXISTS attachments CASCADE;
DROP TABLE IF EXISTS test_attempts CASCADE;
DROP TABLE IF EXISTS tests CASCADE;
DROP TABLE IF EXISTS suites CASCADE;
DROP TABLE IF EXISTS run_executions CASCADE;
DROP TABLE IF EXISTS runs CASCADE;
DROP TABLE IF EXISTS run_stats CASCADE;
