#!/command/with-contenv sh
set -eu

install -d -m 0755 -o mongodb -g mongodb /data/mongodb
chown -R mongodb:mongodb /data/mongodb
touch /data/mongodb/mongod.log
chown mongodb:mongodb /data/mongodb/mongod.log

# Run MongoDB as the mongodb user
exec s6-setuidgid mongodb /usr/local/bin/mongod --dbpath /data/mongodb --bind_ip 127.0.0.1 --port 27017 --logpath /data/mongodb/mongod.log
