// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/service.proto

package test_signal_observer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestSignalObserver_SubmitSignal_FullMethodName = "/TestSignalObserver/SubmitSignal"
)

// TestSignalObserverClient is the client API for TestSignalObserver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestSignalObserverClient interface {
	SubmitSignal(ctx context.Context, in *Signal, opts ...grpc.CallOption) (*SignalResponse, error)
}

type testSignalObserverClient struct {
	cc grpc.ClientConnInterface
}

func NewTestSignalObserverClient(cc grpc.ClientConnInterface) TestSignalObserverClient {
	return &testSignalObserverClient{cc}
}

func (c *testSignalObserverClient) SubmitSignal(ctx context.Context, in *Signal, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, TestSignalObserver_SubmitSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestSignalObserverServer is the server API for TestSignalObserver service.
// All implementations must embed UnimplementedTestSignalObserverServer
// for forward compatibility.
type TestSignalObserverServer interface {
	SubmitSignal(context.Context, *Signal) (*SignalResponse, error)
	mustEmbedUnimplementedTestSignalObserverServer()
}

// UnimplementedTestSignalObserverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestSignalObserverServer struct{}

func (UnimplementedTestSignalObserverServer) SubmitSignal(context.Context, *Signal) (*SignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitSignal not implemented")
}
func (UnimplementedTestSignalObserverServer) mustEmbedUnimplementedTestSignalObserverServer() {}
func (UnimplementedTestSignalObserverServer) testEmbeddedByValue()                            {}

// UnsafeTestSignalObserverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestSignalObserverServer will
// result in compilation errors.
type UnsafeTestSignalObserverServer interface {
	mustEmbedUnimplementedTestSignalObserverServer()
}

func RegisterTestSignalObserverServer(s grpc.ServiceRegistrar, srv TestSignalObserverServer) {
	// If the following call pancis, it indicates UnimplementedTestSignalObserverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestSignalObserver_ServiceDesc, srv)
}

func _TestSignalObserver_SubmitSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Signal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestSignalObserverServer).SubmitSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestSignalObserver_SubmitSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestSignalObserverServer).SubmitSignal(ctx, req.(*Signal))
	}
	return interceptor(ctx, in, info, handler)
}

// TestSignalObserver_ServiceDesc is the grpc.ServiceDesc for TestSignalObserver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestSignalObserver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TestSignalObserver",
	HandlerType: (*TestSignalObserverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitSignal",
			Handler:    _TestSignalObserver_SubmitSignal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
