// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/stanterprise/observer/internal/models"
)

// Pagination information
type PageInfo struct {
	// Whether there are more pages
	HasNextPage bool `json:"hasNextPage"`
	// Total count of items
	TotalCount int `json:"totalCount"`
}

// Query root type
type Query struct{}

// Statistics for a test run
type RunStats struct {
	// Total number of tests
	TotalTests int `json:"totalTests"`
	// Number of passed tests
	PassedTests int `json:"passedTests"`
	// Number of failed tests
	FailedTests int `json:"failedTests"`
	// Number of skipped tests
	SkippedTests int `json:"skippedTests"`
	// Total number of steps
	TotalSteps int `json:"totalSteps"`
	// Latest test execution time
	LatestUpdate *time.Time `json:"latestUpdate,omitempty"`
}

// Input for filtering test cases
type TestCaseFilter struct {
	// Filter by run ID
	RunID *string `json:"runId,omitempty"`
	// Filter by status
	Status *string `json:"status,omitempty"`
	// Search by title (case-insensitive)
	TitleContains *string `json:"titleContains,omitempty"`
}

// TestCaseRun connection for pagination
type TestCaseConnection struct {
	// List of test case runs
	Nodes []*models.Test `json:"nodes"`
	// Pagination information
	PageInfo *PageInfo `json:"pageInfo"`
}

type TestConnection = TestCaseConnection

// TestStatus represents the status of a test execution
type TestStatus string

const (
	TestStatusPassed      TestStatus = "PASSED"
	TestStatusFailed      TestStatus = "FAILED"
	TestStatusSkipped     TestStatus = "SKIPPED"
	TestStatusRunning     TestStatus = "RUNNING"
	TestStatusPending     TestStatus = "PENDING"
	TestStatusBroken      TestStatus = "BROKEN"
	TestStatusTimedout    TestStatus = "TIMEDOUT"
	TestStatusInterrupted TestStatus = "INTERRUPTED"
)

var AllTestStatus = []TestStatus{
	TestStatusPassed,
	TestStatusFailed,
	TestStatusSkipped,
	TestStatusRunning,
	TestStatusPending,
	TestStatusBroken,
	TestStatusTimedout,
	TestStatusInterrupted,
}

func (e TestStatus) IsValid() bool {
	switch e {
	case TestStatusPassed, TestStatusFailed, TestStatusSkipped, TestStatusRunning, TestStatusPending, TestStatusBroken, TestStatusTimedout, TestStatusInterrupted:
		return true
	}
	return false
}

func (e TestStatus) String() string {
	return string(e)
}

func (e *TestStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TestStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TestStatus", str)
	}
	return nil
}

func (e TestStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TestStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TestStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
