package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/stanterprise/observer/internal/models"
	"github.com/stanterprise/observer/pkg/api/graph/model"
	"go.mongodb.org/mongo-driver/bson"
)

// TestCase is the resolver for the testCase field.
func (r *queryResolver) TestCase(ctx context.Context, id string) (*models.TestCaseRun, error) {
	// Stub implementation - GraphQL is not currently used
	r.logger.Warn("GraphQL testCase resolver called but not fully implemented", "id", id)
	return nil, fmt.Errorf("GraphQL API not implemented - use REST API at /api/tests/%s", id)
}

// TestCases is the resolver for the testCases field.
func (r *queryResolver) TestCases(ctx context.Context, filter *model.TestCaseFilter, limit *int, offset *int) (*model.TestCaseRunConnection, error) {
	// Stub implementation - GraphQL is not currently used
	r.logger.Warn("GraphQL testCases resolver called but not fully implemented")
	return &model.TestCaseRunConnection{
		Nodes: []*models.TestCaseRun{},
		PageInfo: &model.PageInfo{
			HasNextPage: false,
			TotalCount:  0,
		},
	}, nil
}

// Step is the resolver for the step field.
func (r *queryResolver) Step(ctx context.Context, id string) (*models.StepRun, error) {
	// Stub implementation - GraphQL is not currently used
	r.logger.Warn("GraphQL step resolver called but not fully implemented", "id", id)
	return nil, fmt.Errorf("GraphQL API not implemented")
}

// TestRuns is the resolver for the testRuns field.
func (r *queryResolver) TestRuns(ctx context.Context, limit *int, offset *int) ([]string, error) {
	// Use MongoDB repository to list run IDs
	limitVal := int64(20)
	offsetVal := int64(0)
	if limit != nil && *limit > 0 {
		limitVal = int64(*limit)
	}
	if offset != nil && *offset >= 0 {
		offsetVal = int64(*offset)
	}

	docs, _, err := r.repo.ListTestRuns(ctx, bson.M{}, limitVal, offsetVal)
	if err != nil {
		r.logger.Error("failed to fetch test runs", "error", err)
		return nil, err
	}

	runIDs := make([]string, 0, len(docs))
	for _, doc := range docs {
		runIDs = append(runIDs, doc.ID)
	}

	return runIDs, nil
}

// RunStats is the resolver for the runStats field.
func (r *queryResolver) RunStats(ctx context.Context, runID string) (*model.RunStats, error) {
	stats := &model.RunStats{}

	// Get test run document
	doc, err := r.repo.GetTestRun(ctx, runID)
	if err != nil {
		r.logger.Error("failed to fetch test run for stats", "run_id", runID, "error", err)
		return nil, err
	}

	// Count tests by status
	stats.TotalTests = len(doc.Tests)
	for _, tc := range doc.Tests {
		switch tc.Status {
		case "PASSED":
			stats.PassedTests++
		case "FAILED":
			stats.FailedTests++
		case "SKIPPED":
			stats.SkippedTests++
		}
		// Track latest update
		if stats.LatestUpdate == nil || tc.UpdatedAt.After(*stats.LatestUpdate) {
			stats.LatestUpdate = &tc.UpdatedAt
		}
	}

	// Count total steps across all tests
	totalSteps := 0
	for _, tc := range doc.Tests {
		totalSteps += len(tc.Steps)
	}
	stats.TotalSteps = totalSteps

	return stats, nil
}

// Metadata is the resolver for the metadata field.
func (r *stepRunResolver) Metadata(ctx context.Context, obj *models.StepRun) (*string, error) {
	// StepRun (StepDocument) doesn't have metadata in current schema
	return nil, nil
}

// Error is the resolver for the error field.
func (r *stepRunResolver) Error(ctx context.Context, obj *models.StepRun) (*string, error) {
	// StepRun doesn't have error field in current schema
	return nil, nil
}

// TestCase is the resolver for the testCase field.
func (r *stepRunResolver) TestCase(ctx context.Context, obj *models.StepRun) (*models.TestCaseRun, error) {
	// Find parent test case using GetTestFromRun
	test, err := r.repo.GetTestFromRun(ctx, obj.TestCaseRunID)
	if err != nil {
		r.logger.Error("failed to fetch parent test case", "test_case_run_id", obj.TestCaseRunID, "error", err)
		return nil, err
	}
	return test, nil
}

// Metadata is the resolver for the metadata field.
func (r *testCaseRunResolver) Metadata(ctx context.Context, obj *models.TestCaseRun) (*string, error) {
	if len(obj.Metadata) == 0 {
		return nil, nil
	}
	// Convert metadata to JSON string
	jsonBytes, err := json.Marshal(obj.Metadata)
	if err != nil {
		r.logger.Error("failed to marshal metadata", "id", obj.ID, "error", err)
		return nil, err
	}
	jsonStr := string(jsonBytes)
	return &jsonStr, nil
}

// Error is the resolver for the error field.
func (r *testCaseRunResolver) Error(ctx context.Context, obj *models.TestCaseRun) (*string, error) {
	// TestCaseRun doesn't have error field in current schema
	return nil, nil
}

// Steps is the resolver for the steps field.
func (r *testCaseRunResolver) Steps(ctx context.Context, obj *models.TestCaseRun) ([]*models.StepRun, error) {
	// Steps are embedded in the test document
	return obj.Steps, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// StepRun returns StepRunResolver implementation.
func (r *Resolver) StepRun() StepRunResolver { return &stepRunResolver{r} }

// TestCaseRun returns TestCaseRunResolver implementation.
func (r *Resolver) TestCaseRun() TestCaseRunResolver { return &testCaseRunResolver{r} }

type queryResolver struct{ *Resolver }
type stepRunResolver struct{ *Resolver }
type testCaseRunResolver struct{ *Resolver }
