package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/stanterprise/observer/internal/models"
	"github.com/stanterprise/observer/pkg/api/graph/model"
)

// TestCase is the resolver for the testCase field.
func (r *queryResolver) TestCase(ctx context.Context, id string) (*models.Test, error) {
	// Stub implementation - GraphQL is not currently used
	r.logger.Warn("GraphQL testCase resolver called but not fully implemented", "id", id)
	return nil, fmt.Errorf("GraphQL API not implemented - use REST API at /api/tests/%s", id)
}

// TestCases is the resolver for the testCases field.
func (r *queryResolver) TestCases(ctx context.Context, filter *model.TestCaseFilter, limit *int, offset *int) (*model.TestCaseConnection, error) {
	// Stub implementation - GraphQL is not currently used
	r.logger.Warn("GraphQL testCases resolver called but not fully implemented")
	return &model.TestCaseConnection{
		Nodes: []*models.Test{},
		PageInfo: &model.PageInfo{
			HasNextPage: false,
			TotalCount:  0,
		},
	}, nil
}

// Step is the resolver for the step field.
func (r *queryResolver) Step(ctx context.Context, id string) (*models.StepDocument, error) {
	// Stub implementation - GraphQL is not currently used
	r.logger.Warn("GraphQL step resolver called but not fully implemented", "id", id)
	return nil, fmt.Errorf("GraphQL API not implemented")
}

// TestRuns is the resolver for the testRuns field.
func (r *queryResolver) TestRuns(ctx context.Context, limit *int, offset *int) ([]string, error) {
	r.logger.Warn("GraphQL testRuns resolver called but not implemented")
	return []string{}, nil
}

// RunStats is the resolver for the runStats field.
func (r *queryResolver) RunStats(ctx context.Context, runID string) (*model.RunStats, error) {
	r.logger.Warn("GraphQL runStats resolver called but not implemented", "run_id", runID)
	return &model.RunStats{}, nil
}

// Metadata is the resolver for the metadata field.
func (r *stepRunResolver) Metadata(ctx context.Context, obj *models.StepDocument) (*string, error) {
	if len(obj.Metadata) == 0 {
		return nil, nil
	}
	jsonBytes, err := json.Marshal(obj.Metadata)
	if err != nil {
		r.logger.Error("failed to marshal step metadata", "id", obj.ID, "error", err)
		return nil, err
	}
	jsonStr := string(jsonBytes)
	return &jsonStr, nil
}

// Error is the resolver for the error field.
func (r *stepRunResolver) Error(ctx context.Context, obj *models.StepDocument) (*string, error) {
	if obj.Error == "" {
		return nil, nil
	}
	return &obj.Error, nil
}

// TestCase is the resolver for the testCase field.
func (r *stepRunResolver) TestCase(ctx context.Context, obj *models.StepDocument) (*models.Test, error) {
	r.logger.Warn("GraphQL stepRun.testCase resolver called but not implemented", "test_case_run_id", obj.TestCaseRunID)
	return nil, fmt.Errorf("GraphQL API not implemented")
}

// Metadata is the resolver for the metadata field.
func (r *testResolver) Metadata(ctx context.Context, obj *models.Test) (*string, error) {
	if len(obj.Metadata) == 0 {
		return nil, nil
	}
	// Convert metadata to JSON string
	jsonBytes, err := json.Marshal(obj.Metadata)
	if err != nil {
		r.logger.Error("failed to marshal metadata", "id", obj.ID, "error", err)
		return nil, err
	}
	jsonStr := string(jsonBytes)
	return &jsonStr, nil
}

// Error is the resolver for the error field.
func (r *testResolver) Error(ctx context.Context, obj *models.Test) (*string, error) {
	if len(obj.Attempts) == 0 || obj.RetryIndex == nil {
		return nil, nil
	}
	for i := range obj.Attempts {
		if obj.Attempts[i].AttemptIndex == *obj.RetryIndex && obj.Attempts[i].ErrorMessage != "" {
			return &obj.Attempts[i].ErrorMessage, nil
		}
	}
	return nil, nil
}

// Steps is the resolver for the steps field.
func (r *testResolver) Steps(ctx context.Context, obj *models.Test) ([]*models.StepDocument, error) {
	return []*models.StepDocument{}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// StepRun returns StepRunResolver implementation.
func (r *Resolver) StepRun() StepRunResolver { return &stepRunResolver{r} }

// Test returns TestResolver implementation.
func (r *Resolver) Test() TestResolver { return &testResolver{r} }

type (
	queryResolver   struct{ *Resolver }
	stepRunResolver struct{ *Resolver }
	testResolver    struct{ *Resolver }
)
