{{- if and .Values.ingress.managedCertificate.enabled (or .Values.ingress.ssl.redirect (ne .Values.ingress.ssl.policy "")) }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ include "observer.fullname" . }}-frontend
  labels:
    {{- include "observer.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.ssl.redirect }}
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
  {{- end }}
  {{- if and .Values.ingress.ssl.policy (ne .Values.ingress.ssl.policy "") }}
  sslPolicy: {{ .Values.ingress.ssl.policy }}
  {{- end }}
{{- end }}
