{{- if and .Values.gateway.enabled .Values.gateway.tls.enabled }}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.gateway.tls.certificateName }}
  labels:
    {{- include "observer.labels" . | nindent 4 }}
spec:
  domains:
  {{- if .Values.gateway.web.enabled }}
  - {{ .Values.gateway.web.hostname }}
  {{- end }}
  {{- if .Values.gateway.api.enabled }}
  - {{ .Values.gateway.api.hostname }}
  {{- end }}
  {{- if .Values.gateway.grpc.enabled }}
  - {{ .Values.gateway.grpc.hostname }}
  {{- end }}
{{- end }}
