{{- if and (eq .Values.mode "aio") .Values.aio.grpcLoadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observer.fullname" . }}-grpc-lb
  labels:
    {{- include "observer.labels" . | nindent 4 }}
    app.kubernetes.io/component: grpc-loadbalancer
  {{- with .Values.aio.grpcLoadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  {{- if .Values.aio.grpcLoadBalancer.loadBalancerIP }}
  loadBalancerIP: {{ .Values.aio.grpcLoadBalancer.loadBalancerIP }}
  {{- end }}
  {{- if .Values.aio.grpcLoadBalancer.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.aio.grpcLoadBalancer.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
  - name: grpc
    port: {{ .Values.aio.grpcLoadBalancer.port }}
    targetPort: grpc
    protocol: TCP
  selector:
    {{- include "observer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: aio
{{- end }}
