{{/*
Web UI Ingress
*/}}
{{- if .Values.ingress.web.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "observer.fullname" . }}-web
  labels:
    {{- include "observer.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  annotations:
    {{- if .Values.ingress.managedCertificate.enabled }}
    networking.gke.io/managed-certificates: {{ include "observer.fullname" . }}-cert
    kubernetes.io/ingress.allow-http: "true"
    {{- if or .Values.ingress.ssl.redirect .Values.ingress.ssl.policy }}
    networking.gke.io/v1beta1.FrontendConfig: {{ include "observer.fullname" . }}-frontend
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.web.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.web.className }}
  ingressClassName: {{ .Values.ingress.web.className }}
  {{- end }}
  {{- if .Values.ingress.web.tls }}
  tls:
    {{- range .Values.ingress.web.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.web.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if eq $.Values.mode "aio" }}
                name: {{ include "observer.fullname" $ }}-aio
                {{- else }}
                name: {{ include "observer.fullname" $ }}-web
                {{- end }}
                port:
                  number: 80
          {{- end }}
    {{- end }}
{{- end }}
---
{{/*
API Ingress
*/}}
{{- if .Values.ingress.api.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "observer.fullname" . }}-api
  labels:
    {{- include "observer.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    {{- if .Values.ingress.managedCertificate.enabled }}
    networking.gke.io/managed-certificates: {{ include "observer.fullname" . }}-cert
    kubernetes.io/ingress.allow-http: "true"
    {{- if or .Values.ingress.ssl.redirect .Values.ingress.ssl.policy }}
    networking.gke.io/v1beta1.FrontendConfig: {{ include "observer.fullname" . }}-frontend
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.api.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.api.className }}
  ingressClassName: {{ .Values.ingress.api.className }}
  {{- end }}
  {{- if .Values.ingress.api.tls }}
  tls:
    {{- range .Values.ingress.api.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.api.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if eq $.Values.mode "aio" }}
                name: {{ include "observer.fullname" $ }}-aio
                port:
                  number: 8080
                {{- else }}
                name: {{ include "observer.fullname" $ }}-api
                port:
                  number: 8080
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
---
{{/*
gRPC Ingress
*/}}
{{- if .Values.ingress.grpc.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "observer.fullname" . }}-grpc
  labels:
    {{- include "observer.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
  annotations:
    {{- if .Values.ingress.managedCertificate.enabled }}
    networking.gke.io/managed-certificates: {{ include "observer.fullname" . }}-cert
    kubernetes.io/ingress.allow-http: "true"
    {{- end }}
    {{- if .Values.ingress.grpc.backendConfig.enabled }}
    cloud.google.com/backend-config: '{"default": "{{ include "observer.fullname" . }}-grpc-backend"}'
    {{- end }}
    {{- with .Values.ingress.grpc.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.grpc.className }}
  ingressClassName: {{ .Values.ingress.grpc.className }}
  {{- end }}
  {{- if .Values.ingress.grpc.tls }}
  tls:
    {{- range .Values.ingress.grpc.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.grpc.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if eq $.Values.mode "aio" }}
                name: {{ include "observer.fullname" $ }}-aio
                {{- else }}
                name: {{ include "observer.fullname" $ }}-ingestion
                {{- end }}
                port:
                  number: 50051
          {{- end }}
    {{- end }}
{{- end }}
