{{- if and .Values.ingress.managedCertificate.enabled (or .Values.ingress.web.enabled .Values.ingress.api.enabled .Values.ingress.grpc.enabled) }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "observer.fullname" . }}-cert
  labels:
    {{- include "observer.labels" . | nindent 4 }}
spec:
  domains:
    {{- if .Values.ingress.web.enabled }}
    {{- range .Values.ingress.web.hosts }}
    - {{ .host }}
    {{- end }}
    {{- end }}
    {{- if .Values.ingress.api.enabled }}
    {{- range .Values.ingress.api.hosts }}
    - {{ .host }}
    {{- end }}
    {{- end }}
    {{- if .Values.ingress.grpc.enabled }}
    {{- range .Values.ingress.grpc.hosts }}
    - {{ .host }}
    {{- end }}
    {{- end }}
{{- end }}
